Repository AgileHub-DQ/Backend, pull requests merged in 2024-04, with the labels that each got.

#51 [#50] 이슈 삭제, 수정 API 구현
  src/main/java/dynamicquad/agilehub/global/exception/ExceptionAdvice.java
  src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
  src/main/java/dynamicquad/agilehub/global/util/PhotoS3Manager.java
  src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
  src/main/java/dynamicquad/agilehub/issue/controller/request/IssueRequest.java
  src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
  src/main/java/dynamicquad/agilehub/issue/domain/epic/Epic.java
  src/main/java/dynamicquad/agilehub/issue/domain/image/ImageRepository.java
  src/main/java/dynamicquad/agilehub/issue/domain/story/Story.java
  src/main/java/dynamicquad/agilehub/issue/domain/task/Task.java
  src/main/java/dynamicquad/agilehub/issue/service/ImageService.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueService.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueValidator.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/EpicFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/IssueFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/StoryFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/TaskFactory.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectService.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectValidator.java
  src/main/resources/application-test.yml
  src/test/java/dynamicquad/agilehub/issue/domain/image/ImageRepositoryTest.java
  src/test/java/dynamicquad/agilehub/issue/service/ImageServiceTest.java
  src/test/java/dynamicquad/agilehub/issue/service/IssueServiceTest.java
  src/test/java/dynamicquad/agilehub/issue/service/factory/EpicFactoryTest.java
Labels: :seedling: 기능추가

#53 [#52] 이슈 내 코멘트 API 구현
  src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
  src/main/java/dynamicquad/agilehub/issue/comment/CommentController.java
  src/main/java/dynamicquad/agilehub/issue/comment/domain/Comment.java
  src/main/java/dynamicquad/agilehub/issue/comment/domain/CommentRepository.java
  src/main/java/dynamicquad/agilehub/issue/comment/request/CommentRequest.java
  src/main/java/dynamicquad/agilehub/issue/comment/response/CommentResponse.java
  src/main/java/dynamicquad/agilehub/issue/comment/service/CommentQueryService.java
  src/main/java/dynamicquad/agilehub/issue/comment/service/CommentService.java
  src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectValidator.java
  src/test/java/dynamicquad/agilehub/issue/comment/CommentServiceTest.java
  src/test/java/dynamicquad/agilehub/issue/comment/domain/CommentRepositoryTest.java
Labels: :seedling: 기능추가

#55 [#54] 기본적인 스프린트 기능 API 구현
  src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
  src/main/java/dynamicquad/agilehub/issue/comment/service/CommentQueryService.java
  src/main/java/dynamicquad/agilehub/issue/comment/service/CommentService.java
  src/main/java/dynamicquad/agilehub/issue/domain/IssueRepository.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueService.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueValidator.java
  src/main/java/dynamicquad/agilehub/project/domain/ProjectRepository.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectValidator.java
  src/main/java/dynamicquad/agilehub/sprint/SprintQueryService.java
  src/main/java/dynamicquad/agilehub/sprint/SprintService.java
  src/main/java/dynamicquad/agilehub/sprint/SprintValidator.java
  src/main/java/dynamicquad/agilehub/sprint/controller/SprintController.java
  src/main/java/dynamicquad/agilehub/sprint/controller/SprintRequest.java
  src/main/java/dynamicquad/agilehub/sprint/controller/response/SprintResponse.java
  src/main/java/dynamicquad/agilehub/sprint/domain/Sprint.java
  src/main/java/dynamicquad/agilehub/sprint/domain/SprintRepository.java
  src/main/java/dynamicquad/agilehub/sprint/domain/SprintStatus.java
  src/main/resources/shema.sql
  src/test/java/dynamicquad/agilehub/project/domain/ProjectRepositoryTest.java
  src/test/java/dynamicquad/agilehub/sprint/SprintQueryServiceTest.java
  src/test/java/dynamicquad/agilehub/sprint/SprintServiceTest.java
  src/test/java/dynamicquad/agilehub/sprint/controller/SprintControllerTest.java
  src/test/java/dynamicquad/agilehub/sprint/domain/SprintRepositoryTest.java
Labels: :seedling: 기능추가

#57 [#56] 멤버 로직이 필요한 부분 TODO 추가
  src/main/java/dynamicquad/agilehub/issue/comment/CommentController.java
  src/main/java/dynamicquad/agilehub/issue/comment/service/CommentService.java
  src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
  src/main/java/dynamicquad/agilehub/issue/service/ImageService.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueService.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/EpicFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/StoryFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/TaskFactory.java
  src/main/java/dynamicquad/agilehub/project/controller/ProjectController.java
  src/main/java/dynamicquad/agilehub/project/controller/response/ProjectResponse.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectQueryService.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectService.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectValidator.java
  src/main/java/dynamicquad/agilehub/sprint/controller/SprintController.java
  src/main/java/dynamicquad/agilehub/sprint/controller/request/SprintRequest.java
  src/main/java/dynamicquad/agilehub/sprint/service/SprintQueryService.java
  src/main/java/dynamicquad/agilehub/sprint/service/SprintService.java
  src/main/java/dynamicquad/agilehub/sprint/service/SprintValidator.java
  src/test/java/dynamicquad/agilehub/project/service/ProjectQueryServiceTest.java
  src/test/java/dynamicquad/agilehub/sprint/SprintQueryServiceTest.java
  src/test/java/dynamicquad/agilehub/sprint/SprintServiceTest.java
  src/test/java/dynamicquad/agilehub/sprint/controller/SprintControllerTest.java
Labels: :eagle: 사소한 수정, :hammer: 리팩터링

#64 [#63] 부모 이슈들 simple 조회 api를 구현
  src/main/java/dynamicquad/agilehub/issue/controller/ProjectIssuesController.java
  src/main/java/dynamicquad/agilehub/issue/controller/response/SimpleIssueResponse.java
  src/main/java/dynamicquad/agilehub/issue/domain/epic/EpicRepository.java
  src/main/java/dynamicquad/agilehub/issue/domain/story/StoryRepository.java
  src/main/java/dynamicquad/agilehub/issue/domain/task/TaskRepository.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
Labels: :seedling: 기능추가

#62 [#29] 인증 및 인가로직 구현
  build.gradle
  src/main/java/dynamicquad/agilehub/global/auth/filter/JwtAuthFilter.java
  src/main/java/dynamicquad/agilehub/global/auth/filter/JwtExceptionFilter.java
  src/main/java/dynamicquad/agilehub/global/auth/filter/OAuth2SuccessHandler.java
  src/main/java/dynamicquad/agilehub/global/auth/model/Auth.java
  src/main/java/dynamicquad/agilehub/global/auth/model/GeneratedToken.java
  src/main/java/dynamicquad/agilehub/global/auth/model/JwtRefreshToken.java
  src/main/java/dynamicquad/agilehub/global/auth/model/SecurityMember.java
  src/main/java/dynamicquad/agilehub/global/auth/oauth2info/OAuth2Attribute.java
  src/main/java/dynamicquad/agilehub/global/auth/oauth2info/OAuth2UserInfo.java
  src/main/java/dynamicquad/agilehub/global/auth/repository/RefreshTokenRedisRepository.java
  src/main/java/dynamicquad/agilehub/global/auth/service/CustomOAuth2UserService.java
  src/main/java/dynamicquad/agilehub/global/auth/service/RefreshTokenRedisService.java
  src/main/java/dynamicquad/agilehub/global/auth/util/JwtUtil.java
  src/main/java/dynamicquad/agilehub/global/auth/util/MemberArgumentResolver.java
  src/main/java/dynamicquad/agilehub/global/config/RedisConfig.java
  src/main/java/dynamicquad/agilehub/global/config/SpringSecurityConfig.java
  src/main/java/dynamicquad/agilehub/global/config/SwaggerConfig.java
  src/main/java/dynamicquad/agilehub/global/config/WebConfig.java
  src/main/java/dynamicquad/agilehub/global/exception/JwtException.java
  src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
  src/main/java/dynamicquad/agilehub/issue/comment/service/CommentService.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/EpicFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/StoryFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/TaskFactory.java
  src/main/java/dynamicquad/agilehub/member/converter/MemberConverter.java
  src/main/java/dynamicquad/agilehub/member/domain/Member.java
  src/main/java/dynamicquad/agilehub/member/domain/SocialLogin.java
  src/main/java/dynamicquad/agilehub/member/dto/MemberRequestDto.java
  src/main/java/dynamicquad/agilehub/member/repository/MemberRepository.java
  src/main/java/dynamicquad/agilehub/member/repository/SocialLoginRepository.java
  src/main/java/dynamicquad/agilehub/member/service/MemberQueryService.java
  src/main/java/dynamicquad/agilehub/member/service/MemberService.java
  src/main/java/dynamicquad/agilehub/member/service/SocialLoginQueryService.java
  src/main/java/dynamicquad/agilehub/member/service/SocialLoginService.java
  src/main/java/dynamicquad/agilehub/project/controller/ProjectController.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectQueryService.java
  src/main/resources/application-jwt.yml
  src/main/resources/application-local.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-redis.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/shema.sql
  src/test/java/dynamicquad/agilehub/WithMockCustomUser.java
  src/test/java/dynamicquad/agilehub/WithMockCustomUserSecurityContextFactory.java
  src/test/java/dynamicquad/agilehub/issue/controller/IssueControllerTest.java
  src/test/java/dynamicquad/agilehub/project/controller/ProjectControllerTest.java
  src/test/java/dynamicquad/agilehub/project/domain/MemberProjectRepositoryTest.java
  src/test/java/dynamicquad/agilehub/project/service/ProjectQueryServiceTest.java
  src/test/java/dynamicquad/agilehub/sprint/controller/SprintControllerTest.java
Labels: :seedling: 기능추가

#70 [#69] config 수정
  src/main/java/dynamicquad/agilehub/global/config/SwaggerConfig.java
Labels: :eagle: 사소한 수정

#72 [#71] oauth 성공시 redirect 수정
  src/main/java/dynamicquad/agilehub/global/auth/filter/OAuth2SuccessHandler.java
Labels: :hammer: 리팩터링

#75 [#73] API에 로그인한 멤버를 가지고 필요한 로직들을 추가
  src/main/java/dynamicquad/agilehub/global/auth/util/MemberArgumentResolver.java
  src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
  src/main/java/dynamicquad/agilehub/issue/comment/CommentController.java
  src/main/java/dynamicquad/agilehub/issue/comment/response/CommentResponse.java
  src/main/java/dynamicquad/agilehub/issue/comment/service/CommentService.java
  src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
  src/main/java/dynamicquad/agilehub/issue/controller/ProjectIssuesController.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueService.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/EpicFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/StoryFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/TaskFactory.java
  src/main/java/dynamicquad/agilehub/member/domain/Member.java
  src/main/java/dynamicquad/agilehub/member/dto/MemberRequestDto.java
  src/main/java/dynamicquad/agilehub/member/service/MemberService.java
  src/main/java/dynamicquad/agilehub/project/controller/ProjectController.java
  src/main/java/dynamicquad/agilehub/project/service/MemberProjectService.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectQueryService.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectService.java
  src/main/java/dynamicquad/agilehub/sprint/controller/SprintController.java
  src/main/java/dynamicquad/agilehub/sprint/service/SprintService.java
  src/test/java/dynamicquad/agilehub/issue/comment/CommentServiceTest.java
  src/test/java/dynamicquad/agilehub/issue/service/IssueServiceTest.java
  src/test/java/dynamicquad/agilehub/project/service/ProjectServiceTest.java
  src/test/java/dynamicquad/agilehub/sprint/SprintServiceTest.java
Labels: :seedling: 기능추가, :hammer: 리팩터링

#77 refactor: cors 에러 메서드 수정
  src/main/java/dynamicquad/agilehub/global/config/SpringSecurityConfig.java
Labels: :lady_beetle: 버그, :hammer: 리팩터링

#80 [#78] 간단한 이슈를 조회 API 추가 정보 추가
  src/main/java/dynamicquad/agilehub/issue/controller/ProjectIssuesController.java
  src/main/java/dynamicquad/agilehub/issue/controller/response/IssueResponse.java
  src/main/java/dynamicquad/agilehub/issue/controller/response/SimpleIssueResponse.java
  src/main/java/dynamicquad/agilehub/issue/domain/task/TaskRepository.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
Labels: :seedling: 기능추가, :hammer: 리팩터링
