Repository AgileHub-DQ/Backend, pull requests merged in 2024-05, with the labels that each got.

#82 [#74] 멤버를 이메일로 프로젝트에 초대 구현
  build.gradle
  src/main/java/dynamicquad/agilehub/global/config/MailConfig.java
  src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
  src/main/java/dynamicquad/agilehub/global/mail/model/EmailInfo.java
  src/main/java/dynamicquad/agilehub/global/mail/service/EmailService.java
  src/main/java/dynamicquad/agilehub/global/util/RandomStringUtil.java
  src/main/java/dynamicquad/agilehub/issue/comment/service/CommentQueryService.java
  src/main/java/dynamicquad/agilehub/issue/comment/service/CommentService.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueService.java
  src/main/java/dynamicquad/agilehub/project/controller/ProjectInviteController.java
  src/main/java/dynamicquad/agilehub/project/controller/request/ProjectInviteRequestDto.java
  src/main/java/dynamicquad/agilehub/project/domain/InviteRedisEntity.java
  src/main/java/dynamicquad/agilehub/project/domain/Project.java
  src/main/java/dynamicquad/agilehub/project/domain/ProjectRepository.java
  src/main/java/dynamicquad/agilehub/project/model/InviteEmailInfo.java
  src/main/java/dynamicquad/agilehub/project/repository/InviteRedisRepository.java
  src/main/java/dynamicquad/agilehub/project/service/InviteRedisService.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectInviteService.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectQueryService.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectService.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectValidator.java
  src/main/java/dynamicquad/agilehub/sprint/service/SprintQueryService.java
  src/main/java/dynamicquad/agilehub/sprint/service/SprintService.java
  src/main/resources/application-mail.yml
  src/main/resources/application.yml
  src/main/resources/templates/invite.html
Labels: :seedling: 기능추가

#84 [#83] 이슈 수정 버그 해결 assignee dto image URL 추가
  src/main/java/dynamicquad/agilehub/issue/controller/response/IssueResponse.java
  src/main/java/dynamicquad/agilehub/issue/domain/story/Story.java
  src/main/java/dynamicquad/agilehub/issue/domain/task/Task.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
  src/main/java/dynamicquad/agilehub/sprint/service/SprintQueryService.java
Labels: :lady_beetle: 버그, :hammer: 리팩터링

#89 [#88] imageUrls null 에러 해결
  src/main/java/dynamicquad/agilehub/issue/domain/image/ImageRepository.java
  src/main/java/dynamicquad/agilehub/issue/service/ImageService.java
  src/test/java/dynamicquad/agilehub/issue/service/ImageServiceTest.java
Labels: :lady_beetle: 버그, :hammer: 리팩터링

#90 [#88] S3 image url String 파싱 문제 해결
  src/main/java/dynamicquad/agilehub/global/util/PhotoS3Manager.java
Labels: :lady_beetle: 버그, :hammer: 리팩터링

#91 [#59] 이슈 라벨 추가
  src/main/java/dynamicquad/agilehub/global/config/WebConfig.java
  src/main/java/dynamicquad/agilehub/global/util/StringToIssueLabelConverter.java
  src/main/java/dynamicquad/agilehub/global/util/StringToIssueTypeConverter.java
  src/main/java/dynamicquad/agilehub/issue/controller/request/IssueRequest.java
  src/main/java/dynamicquad/agilehub/issue/controller/response/EpicResponse.java
  src/main/java/dynamicquad/agilehub/issue/controller/response/IssueResponse.java
  src/main/java/dynamicquad/agilehub/issue/controller/response/SimpleIssueResponse.java
  src/main/java/dynamicquad/agilehub/issue/controller/response/StoryResponse.java
  src/main/java/dynamicquad/agilehub/issue/controller/response/TaskResponse.java
  src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
  src/main/java/dynamicquad/agilehub/issue/domain/IssueLabel.java
  src/main/java/dynamicquad/agilehub/issue/domain/epic/Epic.java
  src/main/java/dynamicquad/agilehub/issue/domain/story/Story.java
  src/main/java/dynamicquad/agilehub/issue/domain/task/Task.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/EpicFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/IssueFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/StoryFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/TaskFactory.java
  src/main/java/dynamicquad/agilehub/member/dto/AssigneeDto.java
  src/main/java/dynamicquad/agilehub/sprint/controller/response/SprintResponse.java
  src/main/java/dynamicquad/agilehub/sprint/service/SprintQueryService.java
  src/main/resources/application-local.yml
  src/main/resources/shema.sql
Labels: :seedling: 기능추가, :eagle: 사소한 수정, :hammer: 리팩터링

#93 [#92] readme 초안 작성
  README.md
Labels: :book: 문서

#97 [#87] 프로젝트에 소속된 멤버 리스트로 조회 api 구현
  src/main/java/dynamicquad/agilehub/member/dto/MemberResponseDto.java
  src/main/java/dynamicquad/agilehub/project/controller/ProjectController.java
  src/main/java/dynamicquad/agilehub/project/controller/response/ProjectResponseDto.java
  src/main/java/dynamicquad/agilehub/project/domain/MemberProjectRepository.java
  src/main/java/dynamicquad/agilehub/project/service/MemberProjectService.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectQueryService.java
  src/test/java/dynamicquad/agilehub/project/controller/ProjectControllerTest.java
  src/test/java/dynamicquad/agilehub/project/service/ProjectQueryServiceTest.java
Labels: :seedling: 기능추가

#98 [#96] 엑츄에이터 로그 파일 추출하도록 설정
  .github/workflows/backend-prod-cd.yml
  src/main/java/dynamicquad/agilehub/global/auth/filter/JwtAuthFilter.java
  src/main/java/dynamicquad/agilehub/global/config/SpringSecurityConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/file-error-appender.xml
Labels: :seedling: 기능추가

#100 [#99] 상태 수정 API 추가
  src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
  src/main/java/dynamicquad/agilehub/issue/controller/request/IssueRequest.java
  src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
  src/main/java/dynamicquad/agilehub/issue/domain/IssueStatus.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueService.java
  src/main/resources/application-local.yml
Labels: :rotating_light: 긴급, :seedling: 기능추가

#106 [#104] 테스크에 이미지 링크 및 기간 추가
  src/main/java/dynamicquad/agilehub/issue/domain/Task.java
  src/main/java/dynamicquad/agilehub/issue/dto/IssueResponseDto.java
  src/main/java/dynamicquad/agilehub/issue/dto/backlog/TaskResponseDto.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/TaskFactory.java
  src/main/resources/shema.sql
Labels: :seedling: 기능추가

#109 [#92] docs 수정
  README.md
Labels: :book: 문서

#110 [#103] 이슈 기간 수정 API 구현
  src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
  src/main/java/dynamicquad/agilehub/issue/domain/Epic.java
  src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
  src/main/java/dynamicquad/agilehub/issue/domain/Story.java
  src/main/java/dynamicquad/agilehub/issue/domain/Task.java
  src/main/java/dynamicquad/agilehub/issue/dto/IssueRequestDto.java
  src/main/java/dynamicquad/agilehub/issue/service/command/IssueService.java
  src/main/resources/templates/invite.html
Labels: :seedling: 기능추가, :hammer: 리팩터링

#112 [#111] 스프린트 도메인 리펙터링
  src/main/java/dynamicquad/agilehub/sprint/controller/SprintController.java
  src/main/java/dynamicquad/agilehub/sprint/controller/response/SprintResponse.java
  src/main/java/dynamicquad/agilehub/sprint/dto/SprintRequestDto.java
  src/main/java/dynamicquad/agilehub/sprint/dto/SprintResponseDto.java
  src/main/java/dynamicquad/agilehub/sprint/repository/SprintRepository.java
  src/main/java/dynamicquad/agilehub/sprint/service/SprintValidator.java
  src/main/java/dynamicquad/agilehub/sprint/service/command/SprintService.java
  src/main/java/dynamicquad/agilehub/sprint/service/query/SprintQueryService.java
  src/test/java/dynamicquad/agilehub/sprint/SprintQueryServiceTest.java
  src/test/java/dynamicquad/agilehub/sprint/SprintServiceTest.java
  src/test/java/dynamicquad/agilehub/sprint/controller/SprintControllerTest.java
  src/test/java/dynamicquad/agilehub/sprint/domain/SprintRepositoryTest.java
Labels: :hammer: 리팩터링

#114 [#113] String valueOf로 null 문자 처리
  src/main/java/dynamicquad/agilehub/issue/dto/backlog/StoryResponseDto.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/EpicFactory.java
Labels: :lady_beetle: 버그, :hammer: 리팩터링

#115 [#65] 컨트롤러 테스트 미통과 문제 해결
  src/main/java/dynamicquad/agilehub/global/auth/filter/OAuth2SuccessHandler.java
  src/main/java/dynamicquad/agilehub/global/auth/util/MemberArgumentResolver.java
  src/main/java/dynamicquad/agilehub/global/config/SpringSecurityConfig.java
  src/main/java/dynamicquad/agilehub/member/dto/MemberRequestDto.java
  src/test/java/dynamicquad/agilehub/WithMockCustomUser.java
  src/test/java/dynamicquad/agilehub/WithMockCustomUserSecurityContextFactory.java
  src/test/java/dynamicquad/agilehub/issue/controller/IssueControllerTest.java
  src/test/java/dynamicquad/agilehub/project/controller/ProjectControllerTest.java
  src/test/java/dynamicquad/agilehub/sprint/controller/SprintControllerTest.java
Labels: :test_tube: 테스트, :hammer: 리팩터링

#121 [#120] 이메일 초대 수신 api가 프로젝트 정보를 반환하도록 수정
  src/main/java/dynamicquad/agilehub/project/controller/ProjectInviteController.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectInviteService.java
Labels: :hammer: 리팩터링

#124 feat: 이슈 요약 AI 추가
  src/main/java/dynamicquad/agilehub/global/mail/service/EmailService.java
  src/main/java/dynamicquad/agilehub/global/util/DateUtil.java
  src/main/java/dynamicquad/agilehub/issue/repository/EpicRepository.java
  src/main/java/dynamicquad/agilehub/issue/repository/StoryRepository.java
  src/main/java/dynamicquad/agilehub/issue/repository/TaskRepository.java
  src/main/java/dynamicquad/agilehub/issue/service/query/IssueQueryService.java
  src/main/java/dynamicquad/agilehub/issue/service/query/MonthlyReportDto.java
  src/main/java/dynamicquad/agilehub/report/GptService.java
  src/main/java/dynamicquad/agilehub/report/ReportController.java
  src/main/java/dynamicquad/agilehub/report/ReportService.java
  src/main/java/dynamicquad/agilehub/report/ReportSummaryRequestDto.java
  src/main/java/dynamicquad/agilehub/report/SummaryEmailInfo.java
  src/main/resources/application.yml
  src/main/resources/templates/reportSummary.html
  src/test/java/dynamicquad/agilehub/issue/service/query/IssueQueryServiceTest.java
Labels: :seedling: 기능추가
