Repository AgileHub-DQ/Backend, pull requests merged in 2024-03, with the labels that each got.

#6 [#4] CI/CD workflow 파일 작성
  .github/workflows/backend-prod-cd.yml
  .github/workflows/backend_ci.yml
  Dockerfile
Labels: :seedling: 기능추가

#8 fix: Dockerfile 수정
  Dockerfile
Labels: :lady_beetle: 버그, :hammer: 리팩터링

#11 [#9] runner 2개 사용을 위한 workflow 수정
  .github/workflows/backend-prod-cd.yml
Labels: :hammer: 리팩터링

#14 [#13] application.yml 설정 및 health check api 구현
  Dockerfile
  build.gradle
  src/main/java/dynamicquad/agilehub/global/controller/HealthController.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :seedling: 기능추가, :hammer: 리팩터링

#15 driver 오타 수정
  src/main/resources/application.yml
Labels: :lady_beetle: 버그

#18 [#17] 공통 응답 및 전역 예외 처리 구현
  src/main/java/dynamicquad/agilehub/global/controller/HealthController.java
  src/main/java/dynamicquad/agilehub/global/exception/ExceptionAdvice.java
  src/main/java/dynamicquad/agilehub/global/exception/GeneralException.java
  src/main/java/dynamicquad/agilehub/global/header/CommonResponse.java
  src/main/java/dynamicquad/agilehub/global/header/ReasonDto.java
  src/main/java/dynamicquad/agilehub/global/header/status/BaseStatus.java
  src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
  src/main/java/dynamicquad/agilehub/global/header/status/SuccessStatus.java
Labels: :seedling: 기능추가

#20 [#19] Swagger 적용
  build.gradle
  src/main/java/dynamicquad/agilehub/global/config/SwaggerConfig.java
  src/main/java/dynamicquad/agilehub/global/controller/HealthController.java
  src/main/resources/application.yml
Labels: :seedling: 기능추가

#24 [#12] dockerfile 수정
  Dockerfile
Labels: :hammer: 리팩터링

#23 [#21] api-docs path 추가
  src/main/resources/application.yml
Labels: :eagle: 사소한 수정, :hammer: 리팩터링

#26 [#25] Entity 구현
  src/main/java/dynamicquad/agilehub/AgilehubApplication.java
  src/main/java/dynamicquad/agilehub/global/domain/BaseEntity.java
  src/main/java/dynamicquad/agilehub/issue/domain/Comment.java
  src/main/java/dynamicquad/agilehub/issue/domain/Epic.java
  src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
  src/main/java/dynamicquad/agilehub/issue/domain/IssueStatus.java
  src/main/java/dynamicquad/agilehub/issue/domain/Story.java
  src/main/java/dynamicquad/agilehub/issue/domain/Task.java
  src/main/java/dynamicquad/agilehub/member/domain/Member.java
  src/main/java/dynamicquad/agilehub/member/domain/MemberStatus.java
  src/main/java/dynamicquad/agilehub/project/domain/MemberProject.java
  src/main/java/dynamicquad/agilehub/project/domain/MemberProjectRole.java
  src/main/java/dynamicquad/agilehub/project/domain/Project.java
  src/main/java/dynamicquad/agilehub/sprint/domain/Sprint.java
  src/main/java/dynamicquad/agilehub/sprint/domain/SprintStatus.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/shema.sql
  src/test/java/dynamicquad/agilehub/issue/domain/EpicTest.java
  src/test/java/dynamicquad/agilehub/issue/domain/StoryTest.java
Labels: :seedling: 기능추가

#28 [#27] AWS 환경변수와 같은 변수명으로 수정
  src/main/resources/application.yml
  src/main/resources/shema.sql
Labels: :lady_beetle: 버그, :hammer: 리팩터링

#32 [#30] 프로젝트 생성,조회,수정 API 구현
  src/main/java/dynamicquad/agilehub/AgilehubApplication.java
  src/main/java/dynamicquad/agilehub/global/config/JpaAuditingConfig.java
  src/main/java/dynamicquad/agilehub/global/domain/BaseEntity.java
  src/main/java/dynamicquad/agilehub/global/exception/ExceptionAdvice.java
  src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
  src/main/java/dynamicquad/agilehub/issue/domain/Epic.java
  src/main/java/dynamicquad/agilehub/issue/domain/Story.java
  src/main/java/dynamicquad/agilehub/member/domain/Member.java
  src/main/java/dynamicquad/agilehub/member/domain/MemberRepository.java
  src/main/java/dynamicquad/agilehub/project/controller/ProjectController.java
  src/main/java/dynamicquad/agilehub/project/controller/request/ProjectCreateReq.java
  src/main/java/dynamicquad/agilehub/project/controller/request/ProjectUpdateReq.java
  src/main/java/dynamicquad/agilehub/project/controller/response/ProjectRes.java
  src/main/java/dynamicquad/agilehub/project/domain/MemberProjectRepository.java
  src/main/java/dynamicquad/agilehub/project/domain/Project.java
  src/main/java/dynamicquad/agilehub/project/domain/ProjectRepository.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectService.java
  src/main/java/dynamicquad/agilehub/sprint/domain/Sprint.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/shema.sql
  src/test/java/dynamicquad/agilehub/AgilehubApplicationTests.java
  src/test/java/dynamicquad/agilehub/issue/domain/EpicTest.java
  src/test/java/dynamicquad/agilehub/issue/domain/StoryTest.java
  src/test/java/dynamicquad/agilehub/project/controller/ProjectControllerTest.java
  src/test/java/dynamicquad/agilehub/project/domain/MemberProjectRepositoryTest.java
  src/test/java/dynamicquad/agilehub/project/domain/ProjectRepositoryTest.java
  src/test/java/dynamicquad/agilehub/project/service/ProjectServiceTest.java
Labels: :book: 문서, :seedling: 기능추가

#34 [#31] Logback을 이용해 운영 환경 별 로그 파일 작성
  .github/workflows/backend-prod-cd.yml
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/logback-spring.xml
Labels: :book: 문서, :seedling: 기능추가

#37 [#35] CQRS 패턴 적용와 DTO inner class화
  src/main/java/dynamicquad/agilehub/project/controller/ProjectController.java
  src/main/java/dynamicquad/agilehub/project/controller/request/ProjectCreateReq.java
  src/main/java/dynamicquad/agilehub/project/controller/request/ProjectRequest.java
  src/main/java/dynamicquad/agilehub/project/controller/request/ProjectUpdateReq.java
  src/main/java/dynamicquad/agilehub/project/controller/response/ProjectResponse.java
  src/main/java/dynamicquad/agilehub/project/domain/Project.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectQueryService.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectService.java
  src/test/java/dynamicquad/agilehub/project/controller/ProjectControllerTest.java
  src/test/java/dynamicquad/agilehub/project/service/ProjectQueryServiceTest.java
  src/test/java/dynamicquad/agilehub/project/service/ProjectServiceTest.java
Labels: :hammer: 리팩터링

#39 [#38] s3 image upload 및 삭제 구현
  build.gradle
  src/main/java/dynamicquad/agilehub/global/config/AwsS3Config.java
  src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
  src/main/java/dynamicquad/agilehub/global/util/PhotoManager.java
  src/main/java/dynamicquad/agilehub/global/util/PhotoS3Manager.java
  src/main/resources/application.yml
Labels: :seedling: 기능추가

#42 [#40] 이슈 생성 및 조회 API 구현
  build.gradle
  src/main/java/dynamicquad/agilehub/global/config/SwaggerConfig.java
  src/main/java/dynamicquad/agilehub/global/config/WebConfig.java
  src/main/java/dynamicquad/agilehub/global/exception/ExceptionAdvice.java
  src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
  src/main/java/dynamicquad/agilehub/global/util/PhotoS3Manager.java
  src/main/java/dynamicquad/agilehub/global/util/StringToIssueStatusConverter.java
  src/main/java/dynamicquad/agilehub/global/util/StringToIssueTypeConverter.java
  src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
  src/main/java/dynamicquad/agilehub/issue/controller/IssueResponse.java
  src/main/java/dynamicquad/agilehub/issue/controller/request/IssueRequest.java
  src/main/java/dynamicquad/agilehub/issue/controller/request/IssueType.java
  src/main/java/dynamicquad/agilehub/issue/domain/Epic.java
  src/main/java/dynamicquad/agilehub/issue/domain/Issue.java
  src/main/java/dynamicquad/agilehub/issue/domain/IssueRepository.java
  src/main/java/dynamicquad/agilehub/issue/domain/IssueStatus.java
  src/main/java/dynamicquad/agilehub/issue/domain/image/Image.java
  src/main/java/dynamicquad/agilehub/issue/domain/image/ImageRepository.java
  src/main/java/dynamicquad/agilehub/issue/domain/story/Story.java
  src/main/java/dynamicquad/agilehub/issue/domain/story/StoryRepository.java
  src/main/java/dynamicquad/agilehub/issue/domain/task/Task.java
  src/main/java/dynamicquad/agilehub/issue/domain/task/TaskRepository.java
  src/main/java/dynamicquad/agilehub/issue/service/ImageService.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueService.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/EpicFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/IssueFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/IssueFactoryProvider.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/StoryFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/TaskFactory.java
  src/main/java/dynamicquad/agilehub/project/controller/BoardController.java
  src/main/java/dynamicquad/agilehub/project/controller/ProjectController.java
  src/main/java/dynamicquad/agilehub/project/domain/MemberProjectRepository.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectService.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/shema.sql
  src/test/java/dynamicquad/agilehub/issue/controller/IssueControllerTest.java
  src/test/java/dynamicquad/agilehub/issue/domain/EpicTest.java
  src/test/java/dynamicquad/agilehub/issue/domain/IssueRepositoryTest.java
  src/test/java/dynamicquad/agilehub/issue/domain/StoryTest.java
  src/test/java/dynamicquad/agilehub/issue/service/factory/EpicFactoryTest.java
  src/test/java/dynamicquad/agilehub/issue/service/factory/StoryFactoryTest.java
  src/test/java/dynamicquad/agilehub/issue/service/factory/TaskFactoryTest.java
Labels: :seedling: 기능추가, :hammer: 리팩터링

#43 [#41] Redirect에서 201 Created로 변경
  src/main/java/dynamicquad/agilehub/global/util/PhotoS3Manager.java
  src/main/java/dynamicquad/agilehub/issue/service/ImageService.java
  src/main/java/dynamicquad/agilehub/project/controller/BoardController.java
  src/main/java/dynamicquad/agilehub/project/controller/ProjectController.java
  src/main/resources/application.yml
  src/test/java/dynamicquad/agilehub/issue/service/ImageServiceTest.java
  src/test/java/dynamicquad/agilehub/issue/service/factory/EpicFactoryTest.java
  src/test/java/dynamicquad/agilehub/project/controller/ProjectControllerTest.java
Labels: :eagle: 사소한 수정, :hammer: 리팩터링

#45 [#44] 파일확장자 contentType 수정
  src/main/java/dynamicquad/agilehub/global/header/status/ErrorStatus.java
  src/main/java/dynamicquad/agilehub/global/util/PhotoS3Manager.java
Labels: :hammer: 리팩터링

#47 [#46] 모든 이슈 조회 API 구현
  src/main/java/dynamicquad/agilehub/global/util/PhotoS3Manager.java
  src/main/java/dynamicquad/agilehub/issue/controller/IssueController.java
  src/main/java/dynamicquad/agilehub/issue/controller/request/IssueRequest.java
  src/main/java/dynamicquad/agilehub/issue/controller/response/IssueHierarchyResponse.java
  src/main/java/dynamicquad/agilehub/issue/controller/response/IssueResponse.java
  src/main/java/dynamicquad/agilehub/issue/domain/IssueRepository.java
  src/main/java/dynamicquad/agilehub/issue/domain/epic/Epic.java
  src/main/java/dynamicquad/agilehub/issue/domain/epic/EpicRepository.java
  src/main/java/dynamicquad/agilehub/issue/domain/story/Story.java
  src/main/java/dynamicquad/agilehub/issue/domain/story/StoryRepository.java
  src/main/java/dynamicquad/agilehub/issue/domain/task/TaskRepository.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueHierarchyBuilder.java
  src/main/java/dynamicquad/agilehub/issue/service/IssueQueryService.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/EpicFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/IssueFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/StoryFactory.java
  src/main/java/dynamicquad/agilehub/issue/service/factory/TaskFactory.java
  src/main/java/dynamicquad/agilehub/project/service/ProjectQueryService.java
  src/main/resources/application-test.yml
  src/main/resources/data.sql
  src/main/resources/shema.sql
  src/test/java/dynamicquad/agilehub/issue/domain/EpicTest.java
  src/test/java/dynamicquad/agilehub/issue/domain/IssueRepositoryTest.java
  src/test/java/dynamicquad/agilehub/issue/domain/StoryTest.java
  src/test/java/dynamicquad/agilehub/issue/domain/epic/EpicRepositoryTest.java
  src/test/java/dynamicquad/agilehub/issue/service/ImageServiceTest.java
  src/test/java/dynamicquad/agilehub/issue/service/IssueQueryServiceTest.java
  src/test/java/dynamicquad/agilehub/issue/service/factory/EpicFactoryTest.java
  src/test/java/dynamicquad/agilehub/issue/service/factory/StoryFactoryTest.java
  src/test/java/dynamicquad/agilehub/issue/service/factory/TaskFactoryTest.java
  src/test/java/dynamicquad/agilehub/project/domain/MemberProjectRepositoryTest.java
  src/test/java/dynamicquad/agilehub/project/domain/ProjectRepositoryTest.java
  src/test/java/dynamicquad/agilehub/project/service/ProjectQueryServiceTest.java
  src/test/java/dynamicquad/agilehub/project/service/ProjectServiceTest.java
Labels: :seedling: 기능추가, :hammer: 리팩터링
